brew "bat"
brew "cmake"
brew "coreutils"
brew "esphome"
brew "esptool"
brew "ffmpeg"
brew "gh"
brew "go"
brew "gping"
brew "hugo"
brew "imagemagick"
brew "imessage-exporter"
brew "jq"
brew "openssl"
brew "pipx"
brew "python"
brew "watch"
brew "wget"
brew "yt-dlp"
brew "zsh"
brew "pure" # Prompt for ZSH
brew "zsh-syntax-highlighting" # Syntax highlighting for ZSH
brew "zsh-autosuggestions" # Fish-like autosuggestions for ZSH
brew "zoxide"
brew "fzf"

cask "alfred"
cask "audacity"
cask "balenaetcher"
cask "db-browser-for-sqlite"
cask "grandperspective"
cask "hammerspoon"
cask "inkscape"
cask "insomnium"
cask "keka"
cask "iterm2"
cask "font-jetbrains-mono"

vscode "esphome.esphome-vscode"
vscode "euskadi31.json-pretty-printer"
vscode "keesschollaart.vscode-home-assistant"
vscode "mechatroner.rainbow-csv"
vscode "ms-vscode.hexeditor"
vscode "ryu1kn.partial-diff"
vscode "sysoev.vscode-open-in-github"
